# Generated by Django 5.1.15 on 2026-05-12 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.CharField(help_text='KOPIS 공연 ID (mt20id)', max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='공연명 (prfnm)', max_length=500)),
                ('genre', models.CharField(blank=True, help_text='장르 (genrenm)', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='공연시작일 (prfpdfrom)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='공연종료일 (prfpdto)', null=True)),
                ('status', models.CharField(choices=[('공연예정', '공연예정'), ('공연중', '공연중'), ('공연완료', '공연완료')], default='공연예정', help_text='공연상태 (prfstate)', max_length=20)),
                ('cast', models.TextField(blank=True, help_text='출연진 (prfcast)')),
                ('crew', models.TextField(blank=True, help_text='스태프 (prfcrew)')),
                ('runtime', models.CharField(blank=True, help_text='공연런타임 (prfruntime)', max_length=100)),
                ('age_rating', models.CharField(blank=True, help_text='관람등급 (prfage)', max_length=50)),
                ('price_info', models.TextField(blank=True, help_text='티켓가격 (pcseguidance)')),
                ('schedule_info', models.TextField(blank=True, help_text='공연시간 (dtguidance)')),
                ('poster_url', models.URLField(blank=True, help_text='포스터 이미지 URL', max_length=1000)),
                ('view_count', models.IntegerField(default=0, help_text='누적 조회수')),
                ('zzim_count', models.IntegerField(default=0, help_text='누적 관심저장수')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, help_text='KOPIS 마지막 동기화 시각')),
            ],
            options={
                'verbose_name': '공연',
                'verbose_name_plural': '공연 목록',
                'db_table': 'performances',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.CharField(help_text='KOPIS 공연시설 ID (mt10id)', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='공연시설명', max_length=255)),
                ('sido', models.CharField(blank=True, help_text='시도명', max_length=50)),
                ('gugun', models.CharField(blank=True, help_text='구군명', max_length=50)),
                ('address', models.CharField(blank=True, help_text='주소', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='위도', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='경도', max_digits=10, null=True)),
                ('seat_scale', models.IntegerField(blank=True, help_text='좌석규모', null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, help_text='KOPIS 마지막 동기화 시각')),
            ],
            options={
                'verbose_name': '공연시설',
                'verbose_name_plural': '공연시설 목록',
                'db_table': 'venues',
            },
        ),
        migrations.CreateModel(
            name='BookingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='예매처명 (relatenm)', max_length=100)),
                ('url', models.URLField(help_text='예매 URL (relateurl)', max_length=1000)),
                ('performance', models.ForeignKey(help_text='공연 FK', on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='performances.performance')),
            ],
            options={
                'verbose_name': '예매 링크',
                'db_table': 'booking_links',
            },
        ),
        migrations.CreateModel(
            name='PerformanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='소개 이미지 URL', max_length=1000)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='정렬 순서')),
                ('performance', models.ForeignKey(help_text='공연 FK', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='performances.performance')),
            ],
            options={
                'verbose_name': '공연 소개 이미지',
                'db_table': 'performance_images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='공연시설 FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='performances.venue'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['genre'], name='performance_genre_9f2c88_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['status'], name='performance_status_eb95c7_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['start_date', 'end_date'], name='performance_start_d_57bf89_idx'),
        ),
    ]
