# Generated by Django 5.1.15 on 2026-05-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=models.CharField(choices=[('공연예정', 'upcomming'), ('공연중', 'performing'), ('공연완료', 'done')], default='공연예정', help_text='공연상태 (prfstate)', max_length=20),
        ),
        migrations.CreateModel(
            name='UsersPerformanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('interest', '관심저장'), ('watchlist', '볼예정')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_performance_actions', to='performances.performance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_performance_actions',
                'unique_together': {('user', 'performance', 'action_type')},
            },
        ),
    ]
