# Generated by Django 5.1.15 on 2026-06-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_alter_performance_status_usersperformanceaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='synopsis',
            field=models.TextField(blank=True, help_text='공연 줄거리/소개 (sty)'),
        ),
    ]
