# Generated by Django 5.1.15 on 2026-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_performance_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='agency',
            field=models.CharField(blank=True, help_text='기획사 (entrpsnmA)', max_length=255),
        ),
        migrations.AddField(
            model_name='performance',
            name='facility_name',
            field=models.CharField(blank=True, help_text='공연시설명 원문 (fcltynm)', max_length=255),
        ),
        migrations.AddField(
            model_name='performance',
            name='first_registered_at',
            field=models.DateTimeField(blank=True, help_text='KOPIS 최초 등록일 (frstregdt)', null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='genre_code',
            field=models.CharField(blank=True, help_text='KOPIS 장르 코드 (shcate)', max_length=10),
        ),
        migrations.AddField(
            model_name='performance',
            name='host',
            field=models.CharField(blank=True, help_text='주최 (entrpsnmH)', max_length=255),
        ),
        migrations.AddField(
            model_name='performance',
            name='is_child',
            field=models.BooleanField(default=False, help_text='아동 공연 여부 (child)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='is_daehakro',
            field=models.BooleanField(default=False, help_text='대학로 공연 여부 (daehakro)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='is_festival',
            field=models.BooleanField(default=False, help_text='축제 여부 (festival)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='is_free',
            field=models.BooleanField(default=False, help_text='무료 공연 여부'),
        ),
        migrations.AddField(
            model_name='performance',
            name='is_musical_create',
            field=models.BooleanField(default=False, help_text='창작 뮤지컬 여부 (musicalcreate)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='is_musical_license',
            field=models.BooleanField(default=False, help_text='라이선스 뮤지컬 여부 (musicallicense)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='is_visit',
            field=models.BooleanField(default=False, help_text='내한 여부 (visit)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='kopis_updated_at',
            field=models.DateTimeField(blank=True, help_text='KOPIS 최종 수정일 (updatedate)', null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, help_text='파싱된 최고가', null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, help_text='파싱된 최저가', null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='openrun',
            field=models.BooleanField(default=False, help_text='오픈런 여부 (openrun)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='organizer',
            field=models.CharField(blank=True, help_text='주관 (entrpsnmS)', max_length=255),
        ),
        migrations.AddField(
            model_name='performance',
            name='price_parse_status',
            field=models.CharField(blank=True, help_text='가격 파싱 상태', max_length=20),
        ),
        migrations.AddField(
            model_name='performance',
            name='production_company',
            field=models.CharField(blank=True, help_text='제작사 (entrpsnmP)', max_length=255),
        ),
        migrations.AddField(
            model_name='performance',
            name='stage_id',
            field=models.CharField(blank=True, help_text='공연장 ID (mt13id)', max_length=20),
        ),
        migrations.AddField(
            model_name='performance',
            name='status_code',
            field=models.CharField(blank=True, help_text='KOPIS 공연상태 코드', max_length=10),
        ),
        migrations.AddField(
            model_name='venue',
            name='facility_characteristic',
            field=models.CharField(blank=True, help_text='시설특성 (fcltychartr)', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_parking_lot',
            field=models.BooleanField(default=False, help_text='주차장 보유 여부 (parkinglot)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='homepage_url',
            field=models.URLField(blank=True, help_text='시설 홈페이지 (relateurl)', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['genre_code'], name='performance_genre_c_dd022c_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['status_code'], name='performance_status__971e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['min_price', 'max_price'], name='performance_min_pri_04e6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['is_child'], name='performance_is_chil_2bbc13_idx'),
        ),
    ]
