# Generated by Django 5.1.15 on 2026-06-16 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performances', '0004_performance_agency_performance_facility_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_data', models.JSONField(blank=True, default=dict)),
                ('source_summary', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_vector', to='performances.performance')),
            ],
            options={
                'db_table': 'recommendation_performance_vectors',
            },
        ),
        migrations.CreateModel(
            name='RecommendationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField(blank=True)),
                ('provider', models.CharField(default='rule_based', max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(default='recommendation-v1', max_length=50)),
                ('user_profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('candidate_snapshot', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('parsed_response', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('not_run', 'not_run'), ('passed', 'passed'), ('failed', 'failed'), ('fallback', 'fallback')], default='not_run', max_length=20)),
                ('fallback_used', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('click', 'click'), ('interest', 'interest'), ('watchlist', 'watchlist'), ('booking_link', 'booking_link'), ('thumbs_up', 'thumbs_up'), ('thumbs_down', 'thumbs_down'), ('regenerate', 'regenerate')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_feedback', to='performances.performance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.recommendationsession')),
            ],
            options={
                'db_table': 'recommendation_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_data', models.JSONField(blank=True, default=dict)),
                ('source_summary', models.JSONField(blank=True, default=dict)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('openai', 'openai'), ('candidate', 'candidate'), ('fallback', 'fallback')], default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_items', to='performances.performance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.recommendationsession')),
            ],
            options={
                'db_table': 'recommendation_items',
                'ordering': ['rank', 'id'],
                'unique_together': {('session', 'performance')},
            },
        ),
    ]
