# Generated by Django 5.1.15 on 2026-06-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('click', 'click'), ('interest', 'interest'), ('watchlist', 'watchlist'), ('booking_link', 'booking_link'), ('thumbs_up', 'thumbs_up'), ('thumbs_down', 'thumbs_down'), ('regenerate', 'regenerate'), ('reason_not_helpful', 'reason_not_helpful'), ('not_my_taste', 'not_my_taste'), ('already_seen', 'already_seen')], max_length=30),
        ),
        migrations.CreateModel(
            name='TrainingExampleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('auto_approved', 'auto_approved'), ('needs_review', 'needs_review'), ('rejected', 'rejected'), ('exported', 'exported')], default='needs_review', max_length=30)),
                ('training_task', models.CharField(choices=[('recommendation_reasoning', 'recommendation_reasoning'), ('query_understanding', 'query_understanding')], default='recommendation_reasoning', max_length=50)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('chosen_output', models.JSONField(blank=True, default=dict)),
                ('rejected_output', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.FloatField(default=0)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('approved_for_training', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_training_candidates', to=settings.AUTH_USER_MODEL)),
                ('source_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_candidate', to='recommendations.recommendationsession')),
            ],
            options={
                'db_table': 'recommendation_training_candidates',
                'ordering': ['-quality_score', '-created_at'],
            },
        ),
    ]
