# Generated by Django 5.1.15 on 2026-06-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("performance_review", "공연후기"),
                    ("performance_recommendation", "공연추천"),
                    ("information", "정보공유"),
                    ("free_discussion", "자유토론"),
                ],
                db_index=True,
                default="free_discussion",
                max_length=40,
            ),
        ),
    ]
